# package = crate || lib 
[package]
name = "mygrep"
version = "0.1.0"
authors = ["ges0909 <gerrit.schrader@gmail.com>"]

[lib]
name = "grep"
path = "src/lib.rs"
test = true
doctest = false
bench = false
doc = false
harness = true

[[test]]
name = "test"
path = "src/test/test.rs"
